### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud-samples/eureka#15]
When I run this with mvn spring:boot run I get the exception

```
Error starting ApplicationContext. To display the auto-configuration report enabled debug logging (start with --debug)


2015-04-30 15:29:41.961 ERROR 13958 --- [lication.main()] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Tomcat connector in failed state
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:157)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at eurekademo.EurekaApplication.main(EurekaApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.RunMojo$LaunchRunner.run(RunMojo.java:418)
	at java.lang.Thread.run(Thread.java:745)

2015-04-30 15:29:41.962  INFO 13958 --- [lication.main()] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4a01ee74: startup date [Thu Apr 30 15:29:34 BST 2015]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@732f013c
2015-04-30 15:29:41.963 ERROR 13958 --- [       Thread-3] c.netflix.eureka.cluster.PeerEurekaNode  : Cannot register monitors for Peer eureka node :http://user:{cipher}AQBdTe9vjgOqANyfi+Ke5HYmhFJnuvsGJ+8FOqLgdMdFInJkVRzy9XngylNp9KlX2lwPI13jT7ceDjBs9w4B6A15akQTHHP1q9rWwMcLtVCCKGFgvXSgQF+WWIItxBmIDGG4bSgDYZ6XQWl66T84PxjTBygErpmAjn+X2BWdtWtVmjXzpMQMaHGpiyLPoGIQYF4j9ZGpl16Jx79+j6et6LStksrT3WxQuanhZwIkqZ827+2mlUB3kd5ocW7R0vC3JMGVZlGNfqYQwJIhSJ19lrq4gxm/zbGroYonW3QSHTiRlhlvOdovEua/0dCl6+s0iEHYZCBllr7jikEWmS5Px7U2TG8/eQkjR8pUbSN6OE+OI2ZZUCNOT+mi75ZeeN1OtdQ=@localhost:8761/eureka/

java.net.MalformedURLException: For input string: "{cipher}AQBdTe9vjgOqANyfi+Ke5HYmhFJnuvsGJ+8FOqLgdMdFInJkVRzy9XngylNp9KlX2lwPI13jT7ceDjBs9w4B6A15akQTHHP1q9rWwMcLtVCCKGFgvXSgQF+WWIItxBmIDGG4bSgDYZ6XQWl66T84PxjTBygErpmAjn+X2BWdtWtVmjXzpMQMaHGpiyLPoGIQYF4j9ZGpl16Jx79+j6et6LStksrT3WxQuanhZwIkqZ827+2mlUB3kd5ocW7R0vC3JMGVZlGNfqYQwJIhSJ19lrq4gxm"
	at java.net.URL.<init>(URL.java:620)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at com.netflix.eureka.cluster.PeerEurekaNode.<init>(PeerEurekaNode.java:147)
	at com.netflix.eureka.PeerAwareInstanceRegistry.updatePeerEurekaNodes(PeerAwareInstanceRegistry.java:219)
	at com.netflix.eureka.PeerAwareInstanceRegistry.setupPeerEurekaNodes(PeerAwareInstanceRegistry.java:187)
	at com.netflix.eureka.PeerAwareInstanceRegistry.init(PeerAwareInstanceRegistry.java:156)
	at com.netflix.eureka.PeerAwareInstanceRegistry.<init>(PeerAwareInstanceRegistry.java:144)
	at com.netflix.eureka.PeerAwareInstanceRegistry.<clinit>(PeerAwareInstanceRegistry.java:130)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$RegistryInstanceProxyInitializer.onApplicationEvent(EurekaServerInitializerConfiguration.java:239)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$RegistryInstanceProxyInitializer.onApplicationEvent(EurekaServerInitializerConfiguration.java:221)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$RegistryInstanceProxyInitializer$$EnhancerBySpringCGLIB$$f69c5798.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$2$1.initEurekaEnvironment(EurekaServerInitializerConfiguration.java:172)
	at com.netflix.eureka.EurekaBootStrap.contextInitialized(EurekaBootStrap.java:88)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$2.run(EurekaServerInitializerConfiguration.java:175)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "{cipher}AQBdTe9vjgOqANyfi+Ke5HYmhFJnuvsGJ+8FOqLgdMdFInJkVRzy9XngylNp9KlX2lwPI13jT7ceDjBs9w4B6A15akQTHHP1q9rWwMcLtVCCKGFgvXSgQF+WWIItxBmIDGG4bSgDYZ6XQWl66T84PxjTBygErpmAjn+X2BWdtWtVmjXzpMQMaHGpiyLPoGIQYF4j9ZGpl16Jx79+j6et6LStksrT3WxQuanhZwIkqZ827+2mlUB3kd5ocW7R0vC3JMGVZlGNfqYQwJIhSJ19lrq4gxm"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:216)
	at java.net.URL.<init>(URL.java:615)
	... 18 common frames omitted

2015-04-30 15:29:41.964  INFO 13958 --- [lication.main()] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2015-04-30 15:29:41.966  INFO 13958 --- [       Thread-3] c.n.eureka.PeerAwareInstanceRegistry     : Updating the replica nodes as they seem to have changed from [] to [http://user:{cipher}AQBdTe9vjgOqANyfi+Ke5HYmhFJnuvsGJ+8FOqLgdMdFInJkVRzy9XngylNp9KlX2lwPI13jT7ceDjBs9w4B6A15akQTHHP1q9rWwMcLtVCCKGFgvXSgQF+WWIItxBmIDGG4bSgDYZ6XQWl66T84PxjTBygErpmAjn+X2BWdtWtVmjXzpMQMaHGpiyLPoGIQYF4j9ZGpl16Jx79+j6et6LStksrT3WxQuanhZwIkqZ827+2mlUB3kd5ocW7R0vC3JMGVZlGNfqYQwJIhSJ19lrq4gxm/zbGroYonW3QSHTiRlhlvOdovEua/0dCl6+s0iEHYZCBllr7jikEWmS5Px7U2TG8/eQkjR8pUbSN6OE+OI2ZZUCNOT+mi75ZeeN1OtdQ=@localhost:8761/eureka/] 
2015-04-30 15:29:41.974  INFO 13958 --- [lication.main()] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2015-04-30 15:29:41.974  INFO 13958 --- [lication.main()] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2015-04-30 15:29:41.979  INFO 13958 --- [lication.main()] o.s.c.n.servo.ServoMetricCollector       : Stopping Servo PollScheduler
2015-04-30 15:29:41.990  INFO 13958 --- [lication.main()] c.n.e.EurekaDiscoveryClientConfiguration : Closing DiscoveryClient.jerseyClient
2015-04-30 15:29:41.991  INFO 13958 --- [lication.main()] c.n.e.EurekaDiscoveryClientConfiguration : Removing application eureka from eureka
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.RunMojo$LaunchRunner.run(RunMojo.java:418)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:157)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at eurekademo.EurekaApplication.main(EurekaApplication.java:23)
	... 6 more
2015-04-30 15:29:42.059 ERROR 13958 --- [       Thread-3] com.netflix.eureka.EurekaBootStrap       : Cannot bootstrap eureka server :

java.lang.NullPointerException: null
	at com.netflix.eureka.PeerAwareInstanceRegistry.syncUp(PeerAwareInstanceRegistry.java:262)
	at com.netflix.eureka.PeerAwareInstanceRegistry$$FastClassBySpringCGLIB$$336b8c82.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$RegistryInstanceProxyInitializer$TrafficOpener.invoke(EurekaServerInitializerConfiguration.java:323)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.cloud.netflix.eureka.server.advice.PiggybackMethodInterceptor.invoke(PiggybackMethodInterceptor.java:41)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.netflix.eureka.PeerAwareInstanceRegistry$$EnhancerBySpringCGLIB$$ec9db6ed.syncUp(<generated>)
	at com.netflix.eureka.EurekaBootStrap.contextInitialized(EurekaBootStrap.java:102)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$2.run(EurekaServerInitializerConfiguration.java:175)
	at java.lang.Thread.run(Thread.java:745)

2015-04-30 15:29:42.060 ERROR 13958 --- [       Thread-3] e.s.EurekaServerInitializerConfiguration : Could not initialize Eureka servlet context

java.lang.RuntimeException: Cannot bootstrap eureka server :
	at com.netflix.eureka.EurekaBootStrap.contextInitialized(EurekaBootStrap.java:120)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$2.run(EurekaServerInitializerConfiguration.java:175)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at com.netflix.eureka.PeerAwareInstanceRegistry.syncUp(PeerAwareInstanceRegistry.java:262)
	at com.netflix.eureka.PeerAwareInstanceRegistry$$FastClassBySpringCGLIB$$336b8c82.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$RegistryInstanceProxyInitializer$TrafficOpener.invoke(EurekaServerInitializerConfiguration.java:323)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.cloud.netflix.eureka.server.advice.PiggybackMethodInterceptor.invoke(PiggybackMethodInterceptor.java:41)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.netflix.eureka.PeerAwareInstanceRegistry$$EnhancerBySpringCGLIB$$ec9db6ed.syncUp(<generated>)
	at com.netflix.eureka.EurekaBootStrap.contextInitialized(EurekaBootStrap.java:102)
	... 2 common frames omitted
```

**Comment by nickcodefresh** [comment]
All look like I had something else running on my machine that was interfering with it. Once I rebooted it runs without issue.

**Comment by spencergibb** [comment]
@nickcodefresh do you get it consistently?  I got it once.  I rebuilt and haven't seen it since.  I also recall that sometimes there are issues running eureka with `mvn spring-boot:run`.  Have you tried the jar or running `main` in your ide?

**Comment by spencergibb** [comment]
@nickcodefresh thanks for participating, we appreciate the feedback.
