### ISSUE TITLE
springSTS4.1.x Startup failure, the problem is as follows

### ISSUE THREAD

**Issue by pingdeng** [spring-cloud-samples/eureka#36]
2019-03-05 18:44:32.270  INFO 8804 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7d8704ef: startup date [Tue Mar 05 18:44:32 CST 2019]; root of context hierarchy
2019-03-05 18:44:32.712  INFO 8804 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-03-05 18:44:32.782  INFO 8804 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$dedb1fe] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.2.RELEASE)

2019-03-05 18:44:33.619  INFO 8804 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
2019-03-05 18:44:34.772  INFO 8804 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:8888. Will be trying the next url if available
2019-03-05 18:44:34.773  WARN 8804 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/eureka/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2019-03-05 18:44:34.781  INFO 8804 --- [           main] eurekademo.EurekaApplication             : No active profile set, falling back to default profiles: default
2019-03-05 18:44:34.821  INFO 8804 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5ce8d869: startup date [Tue Mar 05 18:44:34 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@7d8704ef
2019-03-05 18:44:36.531  INFO 8804 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=3385d5ad-1033-3aed-9793-fd1cc046c81b
2019-03-05 18:44:36.581  INFO 8804 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-03-05 18:44:36.863  INFO 8804 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$dedb1fe] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-03-05 18:44:38.064  INFO 8804 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8761 (http)
2019-03-05 18:44:38.107  INFO 8804 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-03-05 18:44:38.107  INFO 8804 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.31
2019-03-05 18:44:38.123  INFO 8804 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Program Files\Java\jdk1.8.0_25\bin;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;D:\oracle_install\app\Administrator\product\11.2.0\dbhome_1\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;D:\Program Files\Java\apache-maven-3.5.0\bin;D:\Program Files\TortoiseSVN\bin;D:\Program Files\Java\jdk1.8.0_25\bin;C:\Program Files (x86)\Tencent\TIM\Bin;C:\Program Files\Git\cmd;C:\Program Files\MySQL\MySQL Server 5.5\bin;D:\Program Files\nodejs\;D:\Program Files\Docker Toolbox;D:\Program Files\Microsoft VS Code Insiders\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;.]
2019-03-05 18:44:38.380  INFO 8804 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-03-05 18:44:38.380  INFO 8804 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3559 ms
2019-03-05 18:44:38.867  INFO 8804 --- [ost-startStop-1] c.n.hystrix.strategy.HystrixPlugins      : Using System Properties for HystrixDynamicProperties! Using class: com.netflix.hystrix.strategy.properties.HystrixDynamicPropertiesSystemProperties
2019-03-05 18:44:41.524  INFO 8804 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2019-03-05 18:44:41.525  INFO 8804 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-03-05 18:44:41.525  INFO 8804 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-03-05 18:44:41.525  INFO 8804 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2019-03-05 18:44:41.525  INFO 8804 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2019-03-05 18:44:41.526  INFO 8804 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2019-03-05 18:44:41.526  INFO 8804 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'servletContainer' to urls: [/eureka/*]
2019-03-05 18:44:41.526  INFO 8804 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2019-03-05 18:44:41.709  INFO 8804 --- [ost-startStop-1] c.s.j.s.i.a.WebApplicationImpl           : Initiating Jersey application, version 'Jersey: 1.19.1 03/11/2016 02:08 PM'
2019-03-05 18:44:41.843  INFO 8804 --- [ost-startStop-1] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2019-03-05 18:44:41.843  INFO 8804 --- [ost-startStop-1] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2019-03-05 18:44:42.170  INFO 8804 --- [ost-startStop-1] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2019-03-05 18:44:42.170  INFO 8804 --- [ost-startStop-1] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2019-03-05 18:44:42.945  INFO 8804 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-03-05 18:44:43.315  INFO 8804 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5ce8d869: startup date [Tue Mar 05 18:44:34 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@7d8704ef
2019-03-05 18:44:43.465  INFO 8804 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-03-05 18:44:43.467  INFO 8804 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-03-05 18:44:43.477  INFO 8804 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/],methods=[GET]}" onto public java.lang.String org.springframework.cloud.netflix.eureka.server.EurekaController.status(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.Object>)
2019-03-05 18:44:43.477  INFO 8804 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/lastn],methods=[GET]}" onto public java.lang.String org.springframework.cloud.netflix.eureka.server.EurekaController.lastn(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.Object>)
2019-03-05 18:44:43.560  INFO 8804 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-03-05 18:44:43.561  INFO 8804 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-03-05 18:44:44.571  INFO 8804 --- [           main] o.s.ui.freemarker.SpringTemplateLoader   : SpringTemplateLoader for FreeMarker: using resource loader [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5ce8d869: startup date [Tue Mar 05 18:44:34 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@7d8704ef] and template loader path [classpath:/templates/]
2019-03-05 18:44:44.573  INFO 8804 --- [           main] o.s.w.s.v.f.FreeMarkerConfigurer         : ClassTemplateLoader for Spring macros added to FreeMarker configuration
2019-03-05 18:44:44.934  INFO 8804 --- [           main] o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
2019-03-05 18:44:45.020  INFO 8804 --- [           main] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
2019-03-05 18:44:45.020  INFO 8804 --- [           main] com.netflix.discovery.DiscoveryClient    : Client configured to neither register nor query for data.
2019-03-05 18:44:45.057  INFO 8804 --- [           main] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1551782685055 with initial instances count: 0
2019-03-05 18:44:45.185  INFO 8804 --- [           main] c.n.eureka.DefaultEurekaServerContext    : Initializing ...
2019-03-05 18:44:45.194  INFO 8804 --- [           main] c.n.eureka.cluster.PeerEurekaNodes       : Adding new peer nodes [http://localhost:8761/eureka/]
2019-03-05 18:44:45.476  INFO 8804 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2019-03-05 18:44:45.476  INFO 8804 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2019-03-05 18:44:45.476  INFO 8804 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2019-03-05 18:44:45.476  INFO 8804 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2019-03-05 18:44:45.765  INFO 8804 --- [           main] c.n.eureka.cluster.PeerEurekaNodes       : Replica node URL:  http://localhost:8761/eureka/
2019-03-05 18:44:45.781  INFO 8804 --- [           main] c.n.e.registry.AbstractInstanceRegistry  : Finished initializing remote region registries. All known remote regions: []
2019-03-05 18:44:45.783  INFO 8804 --- [           main] c.n.eureka.DefaultEurekaServerContext    : Initialized
2019-03-05 18:44:45.815  INFO 8804 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2019-03-05 18:44:45.838  INFO 8804 --- [           main] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[/actuator/health],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2019-03-05 18:44:45.840  INFO 8804 --- [           main] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[/actuator/info],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2019-03-05 18:44:45.841  INFO 8804 --- [           main] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[/actuator],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto protected java.util.Map<java.lang.String, java.util.Map<java.lang.String, org.springframework.boot.actuate.endpoint.web.Link>> org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping.links(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-03-05 18:44:45.970  INFO 8804 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2019-03-05 18:44:45.988  INFO 8804 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
2019-03-05 18:44:45.993  INFO 8804 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2019-03-05 18:44:45.995  INFO 8804 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
2019-03-05 18:44:46.002  INFO 8804 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2019-03-05 18:44:46.019  INFO 8804 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2019-03-05 18:44:46.041  INFO 8804 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=5ce8d869,type=ConfigurationPropertiesRebinder]
2019-03-05 18:44:46.064  INFO 8804 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2019-03-05 18:44:46.071  INFO 8804 --- [           main] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application EUREKA with eureka with status UP
2019-03-05 18:44:46.077  INFO 8804 --- [      Thread-13] o.s.c.n.e.server.EurekaServerBootstrap   : Setting the eureka configuration..
2019-03-05 18:44:46.086 ERROR 8804 --- [      Thread-13] o.s.c.n.e.server.EurekaServerBootstrap   : Cannot bootstrap eureka server :

java.lang.NoClassDefFoundError: com/netflix/config/ConfigurationManager
	at org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap.initEurekaEnvironment(EurekaServerBootstrap.java:111) ~[spring-cloud-netflix-eureka-server-2.0.4.BUILD-SNAPSHOT.jar:2.0.4.BUILD-SNAPSHOT]
	at org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap.contextInitialized(EurekaServerBootstrap.java:82) ~[spring-cloud-netflix-eureka-server-2.0.4.BUILD-SNAPSHOT.jar:2.0.4.BUILD-SNAPSHOT]
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$1.run(EurekaServerInitializerConfiguration.java:71) [spring-cloud-netflix-eureka-server-2.0.4.BUILD-SNAPSHOT.jar:2.0.4.BUILD-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: com.netflix.config.ConfigurationManager
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_25]
	... 4 common frames omitted

2019-03-05 18:44:46.087 ERROR 8804 --- [      Thread-13] e.s.EurekaServerInitializerConfiguration : Could not initialize Eureka servlet context

java.lang.RuntimeException: Cannot bootstrap eureka server :
	at org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap.contextInitialized(EurekaServerBootstrap.java:89) ~[spring-cloud-netflix-eureka-server-2.0.4.BUILD-SNAPSHOT.jar:2.0.4.BUILD-SNAPSHOT]
	at org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration$1.run(EurekaServerInitializerConfiguration.java:71) ~[spring-cloud-netflix-eureka-server-2.0.4.BUILD-SNAPSHOT.jar:2.0.4.BUILD-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: java.lang.NoClassDefFoundError: com/netflix/config/ConfigurationManager
	at org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap.initEurekaEnvironment(EurekaServerBootstrap.java:111) ~[spring-cloud-netflix-eureka-server-2.0.4.BUILD-SNAPSHOT.jar:2.0.4.BUILD-SNAPSHOT]
	at org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap.contextInitialized(EurekaServerBootstrap.java:82) ~[spring-cloud-netflix-eureka-server-2.0.4.BUILD-SNAPSHOT.jar:2.0.4.BUILD-SNAPSHOT]
	... 2 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.netflix.config.ConfigurationManager
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_25]
	... 4 common frames omitted

2019-03-05 18:44:46.163  INFO 8804 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8761 (http) with context path ''
2019-03-05 18:44:46.165  INFO 8804 --- [           main] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 8761
2019-03-05 18:44:46.170  INFO 8804 --- [           main] eurekademo.EurekaApplication             : Started EurekaApplication in 15.842 seconds (JVM running for 16.601)

**Comment by pingdeng** [comment]
哪位大神帮知道什么问题不  ，可以回复邮箱1289010524@qq.com
